# Generated by Django 3.2.7 on 2021-09-18 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=250)),
                ('country', models.CharField(choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland')], default='SK', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('replaced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.membership')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, help_text='Brief description about school.', null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('founder', models.CharField(blank=True, max_length=50, null=True)),
                ('school_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_x', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_y', models.CharField(blank=True, max_length=50, null=True)),
                ('school_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ineko_id', models.CharField(blank=True, max_length=50, null=True)),
                ('underprivileged', models.IntegerField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True)),
                ('mail2', models.CharField(blank=True, max_length=100, null=True)),
                ('mail3', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.address')),
                ('members', models.ManyToManyField(blank=True, through='profiles.Membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('PT', 'Primary School Teacher'), ('ST', 'Secondary School Teacher'), ('S', 'Student'), ('P', 'Parent'), ('L', 'Lecturer'), ('O', 'Other')], max_length=2, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland')], default='SK', max_length=2, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.school'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
