# Generated by Django 3.2.6 on 2021-08-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('PT', 'Primary School Teacher'), ('ST', 'Secondary School Teacher'), ('S', 'Student'), ('P', 'Parent'), ('L', 'Lecturer'), ('O', 'Other')], default='L', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland')], default='SK', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='founder',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='gps_x',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='gps_y',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='ineko_id',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='underprivileged',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland')], default='SK', max_length=2),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description about school.', null=True),
        ),
    ]
