# Generated by Django 3.2.7 on 2021-10-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Metadata about user.', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=250, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland')], default='SK', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=250, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=250, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='effective_from',
            field=models.DateField(blank=True, null=True, verbose_name='Effective from'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='Effective to'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='replaced_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.membership', verbose_name='Replaced by'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('PT', 'Primary School Teacher'), ('ST', 'Secondary School Teacher'), ('S', 'Student'), ('P', 'Parent'), ('L', 'Lecturer'), ('O', 'Other')], max_length=2, null=True, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland')], default='SK', max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description about school.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='school',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='school',
            name='founder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Founder'),
        ),
        migrations.AlterField(
            model_name='school',
            name='gps_x',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GPS X'),
        ),
        migrations.AlterField(
            model_name='school',
            name='gps_y',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GPS Y'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ineko_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ineko ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mail2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 3'),
        ),
        migrations.AlterField(
            model_name='school',
            name='mail3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email 3'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='School code'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='School type'),
        ),
        migrations.AlterField(
            model_name='school',
            name='underprivileged',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unprivileged'),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Website'),
        ),
    ]
