# Generated by Django 3.2.8 on 2022-01-07 18:23

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211008_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), profiles.validators.FileSizeValidator(5)], verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile-headers', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), profiles.validators.FileSizeValidator(5)], verbose_name='Header image'),
        ),
    ]
