# Generated by Django 3.2.8 on 2022-10-14 16:59

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220107_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address note'),
        ),
        migrations.AddField(
            model_name='membership',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='profile-school-proof', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), profiles.validators.FileSizeValidator(5)], verbose_name='Proof'),
        ),
        migrations.AddField(
            model_name='membership',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland'), ('XX', 'Other (insert into note)')], default='SK', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('PT', 'Primary School Teacher'), ('ST', 'Secondary School Teacher'), ('S', 'Student'), ('O', 'Enthusiast')], max_length=2, null=True, verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('SK', 'Slovakia'), ('CZ', 'Czechia'), ('HU', 'Hungary'), ('PL', 'Poland'), ('XX', 'Other (insert into note)')], default='SK', max_length=2, null=True, verbose_name='Country'),
        ),
    ]
