# Generated by Django 3.2.6 on 2021-09-04 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='effective_from',
            field=models.DateField(default=datetime.date(2021, 9, 4)),
        ),
    ]
