name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install {{ matrix.django-version }} -r requirements.txt
    - name: Run unit tests 
      run: |
        pytest tests.py
